files:
  include: '**/*.s+(a|c)ss'
options:
  formatter: stylish
  merge-default-rules: true
rules:
  empty-line-between-blocks: 0
  extends-before-declarations: 1
  extends-before-mixins: 1
  mixins-before-declarations: 1
  nesting-depth: 0
  no-color-literals: 0
  no-important: 0
  no-mergeable-selectors: 1
  no-misspelled-properties:
    - 1
    - extra-properties:
      - 'overflow-scrolling'
      - 'touch-callout'
  no-qualifying-elements:
    - 1
    - allow-element-with-attribute: true
  placeholder-in-extend: 0
  property-sort-order: 0
  no-trailing-whitespace: 0
  force-element-nesting: 0
  force-attribute-nesting: 0
  force-pseudo-nesting: 0
  no-vendor-prefixes: 0
  attribute-quotes: 0
  quotes: 0
  indentation: 0
  
